from typing import Protocol

class INewsletterRepository(Protocol):
    async def add_email(self, email: str, token: str, unsubscribe_token: str) -> None: ...

    async def get_by_token(self, token: str, ): ...

    async def confirm_subscription(self, subscription_id: int) -> None: ...

    async def unsubscribe_by_token(self, token: str) -> bool: ...