from typing import Protocol, Optional, List
from app.domain.model.product import Product  # Twoja domena (nie ORM)
class IProductRepository(Protocol):
    async def get_by_id(self, product_id: int) -> Optional[Product]: ...
    async def get_all(self) -> List[Product]: ...